# file name: problemSetDay2.py
name = input('''What is your name?''')
print(name)
birthday = input('''When is your birthday?''')
print(birthday)
grade = input('''What grade are you in?''')
print(grade)
school = input('''What school do you attend?''')
print(school)
subject = input('''What is your favorite school subject?''')
print(subject)
job = input('''What do you want to be when you grow up?''')
print(job)

a = int(input("What is the value of a?"))
b = int(input("What is the value of b?"))
c = int(input("What is the value of c?"))
print("x = [-b +/- sqrt(b^2 - 2ac)] / 2a")
